version: '3'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 3000:8080
    networks:
      - api
    depends_on:
      - db
      - api.usuarios
  api.usuarios:
    build:
      context: .
      args:
        - FOLDER=./usuarios
    container_name: usuarios
    working_dir: /var/www/project
    command: bash ./init.sh
    networks:
      - api
      - system
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=sch
    ports:
      - "3001:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - system
networks:
  api:
    ipam:
      driver: default
  system:
    ipam:
      driver: default
